spring:
  application:
    name:
      poidocxtest

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:lab_db.db
    username: user
    password: pass
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true

#  datasource:
#    url:
#      jdbc:postgresql://localhost:5432/postgres
#    username:
#      postgres
#    password:
#      root
#    driver-class-name:
#      org.postgresql.Driver
#  jpa:
#    generate-ddl:
#      true
